// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace TypstInterop.Internal
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "typst_interop";





        [DllImport(__DllName, EntryPoint = "typst_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* typst_version();

        [DllImport(__DllName, EntryPoint = "typst_context_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VfsWorld* typst_context_new(byte* main_path, byte packages_source, byte fonts_source, byte* cache_path, byte* data_path);

        [DllImport(__DllName, EntryPoint = "typst_context_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_context_free(VfsWorld* world);

        [DllImport(__DllName, EntryPoint = "typst_context_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_context_reset(VfsWorld* world);

        [DllImport(__DllName, EntryPoint = "typst_set_source", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_source(VfsWorld* world, byte* path, byte* text);

        [DllImport(__DllName, EntryPoint = "typst_set_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_file(VfsWorld* world, byte* path, byte* data, size_t data_len);

        [DllImport(__DllName, EntryPoint = "typst_add_font", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_add_font(VfsWorld* world, byte* data, size_t data_len);

        [DllImport(__DllName, EntryPoint = "typst_set_input", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_input(VfsWorld* world, byte* key, byte* value);

        [DllImport(__DllName, EntryPoint = "typst_set_package_paths", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_package_paths(VfsWorld* world, byte* cache, byte* data);

        [DllImport(__DllName, EntryPoint = "typst_set_package_source", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int typst_set_package_source(VfsWorld* world, byte* package_spec, byte* path, byte* text);

        [DllImport(__DllName, EntryPoint = "typst_set_package_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int typst_set_package_file(VfsWorld* world, byte* package_spec, byte* path, byte* data, size_t data_len);

        [DllImport(__DllName, EntryPoint = "typst_compile_pdf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CompilationResult typst_compile_pdf(VfsWorld* world);

        [DllImport(__DllName, EntryPoint = "typst_free_pdf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_free_pdf(byte* ptr, size_t len);

        [DllImport(__DllName, EntryPoint = "typst_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_free_string(byte* ptr);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VfsWorld
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CompilationResult
    {
        public byte success;
        public byte* pdf_data;
        public size_t pdf_len;
        public byte* error_message;
    }



}
