// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace TypstInterop.Internal
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "typst_interop";





        [DllImport(__DllName, EntryPoint = "typst_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* typst_version();

        /// <summary>
        ///  Create a new VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `main_path`, `cache_path`, `data_path`, and `root_path` must be valid C
        ///  strings if not null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_context_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern VfsWorld* typst_context_new(byte* main_path, byte packages_source, byte fonts_source, byte* cache_path, byte* data_path, byte* root_path);

        /// <summary>
        ///  Free a VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be a valid pointer created by `typst_context_new`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_context_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_context_free(VfsWorld* world);

        /// <summary>
        ///  Reset a VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be a valid pointer to a `VfsWorld`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_context_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_context_reset(VfsWorld* world);

        /// <summary>
        ///  Set (or clear, when null) the real on-disk project root.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `root_path` must be a valid C string if
        ///  not null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_set_root", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_root(VfsWorld* world, byte* root_path);

        /// <summary>
        ///  Set a source file in the VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `path` and `text` must be valid C strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_set_source", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_source(VfsWorld* world, byte* path, byte* text);

        /// <summary>
        ///  Set a binary file in the VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `path` must be a valid C string. `data` must be a valid buffer of `data_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_set_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_file(VfsWorld* world, byte* path, byte* data, size_t data_len);

        /// <summary>
        ///  Add a font to the VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `data` must be a valid buffer of `data_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_add_font", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_add_font(VfsWorld* world, byte* data, size_t data_len);

        /// <summary>
        ///  Set an input variable in the VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `key` and `value` must be valid C strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_set_input", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_input(VfsWorld* world, byte* key, byte* value);

        /// <summary>
        ///  Set package paths in the VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `cache` and `data` must be valid C strings if not null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_set_package_paths", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_set_package_paths(VfsWorld* world, byte* cache, byte* data);

        /// <summary>
        ///  Set a package source file in the VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `package_spec`, `path`, and `text` must be valid C strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_set_package_source", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int typst_set_package_source(VfsWorld* world, byte* package_spec, byte* path, byte* text);

        /// <summary>
        ///  Set a package binary file in the VfsWorld.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `package_spec` and `path` must be valid C strings. `data` must be a valid buffer of `data_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_set_package_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int typst_set_package_file(VfsWorld* world, byte* package_spec, byte* path, byte* data, size_t data_len);

        /// <summary>
        ///  Lists the available font family names, newline-separated. Returns null when
        ///  there are no fonts. The returned string must be freed with `typst_free_string`.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_list_fonts", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* typst_list_fonts(VfsWorld* world);

        /// <summary>
        ///  Compile a document to the format described by `options`.
        ///
        ///  # Safety
        ///
        ///  The `world` pointer must be valid. `options` must point to a valid
        ///  [`CompileOptions`], whose string fields must be valid C strings if not null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_compile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CompilationResult typst_compile(VfsWorld* world, CompileOptions* options);

        /// <summary>
        ///  Free a compilation result and all owned buffers/diagnostics.
        ///
        ///  # Safety
        ///
        ///  `result` must have been produced by `typst_compile` and not freed before.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_free_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_free_result(CompilationResult result);

        /// <summary>
        ///  Free a string.
        ///
        ///  # Safety
        ///
        ///  `ptr` must be a pointer to a string returned by an FFI function.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "typst_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void typst_free_string(byte* ptr);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct VfsWorld
    {
    }

    /// <summary>
    ///  Options controlling a single compilation, passed across the FFI boundary.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CompileOptions
    {
        /// <summary>
        ///  Output format: 0 = PDF, 1 = PNG, 2 = SVG, 3 = HTML.
        /// </summary>
        public byte format;
        /// <summary>
        ///  Pixels per inch for PNG rendering (defaults to 144 if &lt;= 0).
        /// </summary>
        public float ppi;
        /// <summary>
        ///  PDF standard selector (see `pdf_standards_from_code`). 0 = default (PDF 1.7).
        /// </summary>
        public byte pdf_standard;
        /// <summary>
        ///  Whether to embed a fixed timestamp (`use_timestamp` != 0) in the PDF.
        /// </summary>
        public byte use_timestamp;
        /// <summary>
        ///  Unix timestamp (seconds, UTC) to embed when `use_timestamp` is set.
        /// </summary>
        public long timestamp_unix;
        /// <summary>
        ///  Whether to pretty-print SVG/HTML output (!= 0).
        /// </summary>
        public byte pretty;
        /// <summary>
        ///  Document title (UTF-8 C string, may be null).
        /// </summary>
        public byte* title;
        /// <summary>
        ///  Document author (UTF-8 C string, may be null). Single author only.
        /// </summary>
        public byte* author;
    }

    /// <summary>
    ///  A compilation result: the produced outputs plus structured diagnostics.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CompilationResult
    {
        public byte success;
        /// <summary>
        ///  Pointer to an array of `output_count` output buffers.
        /// </summary>
        public OutputBuffer* outputs;
        public size_t output_count;
        /// <summary>
        ///  Pointer to an array of `diagnostic_count` diagnostics (errors + warnings).
        /// </summary>
        public Diagnostic* diagnostics;
        public size_t diagnostic_count;
    }

    /// <summary>
    ///  A single output buffer (a PDF blob, a PNG page, or an SVG/HTML string).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct OutputBuffer
    {
        public byte* data;
        public size_t len;
    }

    /// <summary>
    ///  A structured diagnostic (error or warning) with position information.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Diagnostic
    {
        /// <summary>
        ///  0 = error, 1 = warning.
        /// </summary>
        public byte severity;
        public byte* message;
        /// <summary>
        ///  File path the diagnostic points into, or null when detached.
        /// </summary>
        public byte* file_path;
        /// <summary>
        ///  1-based line number, or 0 when unavailable.
        /// </summary>
        public size_t line;
        /// <summary>
        ///  1-based column number, or 0 when unavailable.
        /// </summary>
        public size_t column;
        /// <summary>
        ///  Newline-separated hint text, or null when there are no hints.
        /// </summary>
        public byte* hints;
    }



}
